#!/bin/bash

GIT_USER="$(git config --global user.name)"
if [[ "$GIT_USER" != "exdeejay" ]]; then
	echo "ERROR: git user.name is set to \"$GIT_USER\""
	echo "Run \`switchgit\` and retry"
	echo "(If you're not DJ, run \`rm .githooks/pre-commit\` to make this message go away)"
	exit 1
fi
