set nocompatible

let mapleader = " "
let g:mapleader = " "

set ignorecase
set smartcase
set backspace=indent,eol,start
set whichwrap+=<,>,h,l
set number
set hlsearch
set incsearch
set magic
set showmatch
set mat=2
set hidden
set splitbelow
set splitright
set nowrap
set encoding=utf8
set display=lastline
"size of <tab>
set tabstop=4
"size of reindenting and << >> ==
set shiftwidth=4
set shiftround
"override filetype plugin (?)
set noexpandtab
"keep indentation of last line
set autoindent
set smartindent
set autoread
au FocusGained,BufEnter * checktime
set wildmenu
set ruler
set cmdheight=1
set ttyfast
set lazyredraw
set mouse=a
set ttymouse=sgr
set ttimeout
set ttimeoutlen=50
set nobackup
set laststatus=2
set writebackup
set noswapfile
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo
"enable filetype plugin
"plugin customization available in ~/.vim/after/ftplugin
filetype plugin on
filetype indent on
syntax on
packadd! matchit

"Airline config
let g:airline_powerline_fonts = 1 
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
let g:airline_theme='deus'

nnoremap <Leader>pp :setlocal paste!<cr>
vnoremap <Leader>y :OSCYank<CR>
nnoremap <Leader>Y v$:OSCYank<CR>
nnoremap <Leader>yy V:OSCYank<CR>
"Split window right
nnoremap <leader>v <C-w>v<C-w>l
"Split window below
nnoremap <leader>s <C-w>s
"Switch windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

set balloonevalterm
" Styled and colored underline support
let &t_AU = "\e[58:5:%dm"
let &t_8u = "\e[58:2:%lu:%lu:%lum"
let &t_Us = "\e[4:2m"
let &t_Cs = "\e[4:3m"
let &t_ds = "\e[4:4m"
let &t_Ds = "\e[4:5m"
let &t_Ce = "\e[4:0m"
" Strikethrough
let &t_Ts = "\e[9m"
let &t_Te = "\e[29m"
" Truecolor support
let &t_8f = "\e[38:2:%lu:%lu:%lum"
let &t_8b = "\e[48:2:%lu:%lu:%lum"
let &t_RF = "\e]10;?\e\\"
let &t_RB = "\e]11;?\e\\"
" Bracketed paste
let &t_BE = "\e[?2004h"
let &t_BD = "\e[?2004l"
let &t_PS = "\e[200~"
let &t_PE = "\e[201~"
" Cursor control
let &t_RC = "\e[?12$p"
let &t_SH = "\e[%d q"
let &t_RS = "\eP$q q\e\\"
let &t_SI = "\e[5 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[1 q"
let &t_VS = "\e[?12l"
" Focus tracking
let &t_fe = "\e[?1004h"
let &t_fd = "\e[?1004l"
" Window title
let &t_ST = "\e[22;2t"
let &t_RT = "\e[23;2t"
" vim hardcodes background color erase even if the terminfo file does
" not contain bce. This causes incorrect background rendering when
" using a color theme with a background color in terminals such as
" kitty that do not support background color erase.
let &t_ut=''

call plug#begin()
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'chr4/nginx.vim'
Plug 'wellle/tmux-complete.vim'
Plug 'mbbill/undotree'
Plug 'ojroques/vim-oscyank'
Plug 'lifepillar/vim-cheat40'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-bufferline'
Plug 'dense-analysis/ale'
Plug 'flazz/vim-colorschemes'
Plug 'nlknguyen/papercolor-theme'
call plug#end()

set background=dark
colorscheme PaperColor

