" To define a mapping which uses the "g:mapleader" variable, the special string "<Leader>" can be used
let mapleader = " "
let g:mapleader = " "

unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim


" ---------- Plugins ---------- "
" Enable matchit stock plugin
packadd! matchit
" Enable manpage viewer plugin
runtime! ftplugin/man.vim
call plug#begin()
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'wellle/tmux-complete.vim'
Plug 'mbbill/undotree'
Plug 'ojroques/vim-oscyank'
Plug 'lifepillar/vim-cheat40'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-bufferline'
Plug 'dense-analysis/ale'
Plug 'tinted-theming/tinted-vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ConradIrwin/vim-bracketed-paste'
Plug 'preservim/nerdcommenter'
Plug 'justinmk/vim-sneak'
call plug#end()
" plug#end() automatically sets filetype plugin indent on and syntax on


" ---------- Options ---------- "
" When set to "dark", Vim will try to use colors that look good on a dark background
set background=dark
" Allow searching for files in subdirectories of vim's cwd
set path+=**
" Ignore case in search patterns
set ignorecase
" Override the 'ignorecase' option if the search pattern contains upper case characters
set smartcase
" Make backspace work across lines and indents
set backspace=indent,eol,start
" Allow left/right movement to work across line breaks
set whichwrap+=<,>,h,l
" Print the line number in front of each line
set number
" Highlight all matches
set hlsearch
" While typing a search command, show where the pattern, as it was typed so far, matches
set incsearch
" When a bracket is inserted, briefly jump to the matching one
set showmatch
" Tenths of a second to show the matching paren, when 'showmatch' is set
set matchtime=2
" When off a buffer is unloaded when it is |abandon|ed
set hidden
" When on, splitting a window will put the new window below the current one
set splitbelow
" When on, splitting a window will put the new window right of the current one
set splitright
" Disable text wrapping
set nowrap
" Maximum width of text that is being inserted 
set textwidth=120
" Sets the character encoding used inside Vim
set encoding=utf-8
" As much as possible of the last line in a window will be displayed.  "@@@" is put in the last columns of the last
" screen line to indicate the rest of the line is not displayed
set display=lastline
" If this many milliseconds nothing is typed the swap file will be written to disk 
set updatetime=300
" Whether or not to draw the signcolumn
set signcolumn=yes
" Display size of \t character
set tabstop=4
" Number of columns inserted by pressing <Tab>
set softtabstop=4
" Size of reindenting and << >> ==
set shiftwidth=4
" Round shift indent to multiple of 'shiftwidth'
set shiftround
" In Insert mode: Use the appropriate number of spaces to insert a <Tab>
set expandtab
" Copy indent from current line when starting a new line
set autoindent
set smartindent
" When a file has been detected to have been changed outside of Vim and it has not been changed inside of Vim,
" automatically read it again with the next two commands
set autoread
au FocusGained,BufEnter * checktime
" When 'wildmenu' is on, command-line completion operates in an enhanced mode
set wildmenu
" Show the line and column number of the cursor position, separated by a comma
set ruler
" Switch on the |balloon-eval| functionality for the terminal
set balloonevalterm
" Number of screen lines to use for the command-line
set cmdheight=1
" Indicates a fast terminal connection
set ttyfast
" When on, uses |highlight-guifg| and |highlight-guibg| attributes in the terminal (thus using 24-bit color).
set termguicolors
" When this option is set, the screen will not be redrawn while executing macros, registers and other commands that have
" not been typed
set lazyredraw
" Enable the use of the mouse
set mouse=a
" Don't ring the bell (beep or screen flash) for error messages
set noerrorbells
" Don't use a visual bell instead of beeping
set novisualbell
" Disable terminal handling of visual bell
set t_vb=
" Name of the terminal type for which mouse codes are to be recognized
set ttymouse=sgr
" Let <Esc> register faster on normal-speed terminals
set ttimeout
set ttimeoutlen=50
" Don't make a backup before overwriting a file
set nobackup
" Always display status line in last window
set laststatus=2
" Make a temporary backup before overwriting a file
set writebackup
" Directory for the swap file, separated with commas
set directory=$HOME/.vim/files/swap/
" After typing this many characters the swap file will be written to disk
set updatecount=100
" When on, Vim automatically saves undo history to an undo file when writing a buffer to a file, and restores undo
" history from the same file on buffer read
set undofile
" List of directory names for undo files, separated with commas
set undodir=$HOME/.vim/files/undo/
" When non-empty, the viminfo file is read upon startup and written when exiting Vim
set viminfo='100,n$HOME/.vim/files/info/viminfo


" ---------- Mappings ---------- "
" Q : format selection
map Q gq
sunmap Q
" <leader>q : swap to last buffer
nnoremap <silent> <leader>q :buffer #<CR>
" <leader>hh : turn off match highlights
nnoremap <silent> <leader>hh :nohl<CR>

" Toggle paste mode (disable autoindent logic)
nnoremap <silent> <leader>pp :setlocal paste!<cr>
" Alternate yank into system clipboard with OSC
" <leader>y : yank selected to system clipboard
vnoremap <silent> <leader>y :OSCYankVisual<CR>
" <leader>Y : yank to end of line to system clipboard
nnoremap <silent> <leader>Y v$:OSCYankVisual<CR>
" <leader>yy : yank whole line to system clipboard
nnoremap <silent> <leader>yy V:OSCYankVisual<CR>
" <leader>v : split window right
nnoremap <leader>v <C-w>v<C-w>l
" <leader>s : split window below
nnoremap <leader>s <C-w>s
" Switch windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Make n and N always search in one direction
" (as opposed to forward/opposite the original search's direction)
nnoremap <expr> n  'Nn'[v:searchforward]
xnoremap <expr> n  'Nn'[v:searchforward]
onoremap <expr> n  'Nn'[v:searchforward]
nnoremap <expr> N  'nN'[v:searchforward]
xnoremap <expr> N  'nN'[v:searchforward]
onoremap <expr> N  'nN'[v:searchforward]

" <leader>m : edit the given register (" if not specified)
nnoremap <leader>m  :<c-u><c-r><c-r>='let @'. v:register .' = '. string(getreg(v:register))<cr><c-f><left>

" Allow visual mode indent shifting to be repeated
xnoremap < <gv
xnoremap > >gv

" Ale commands
nnoremap <silent> <leader>gd :ALEGoToDefinition<CR>
nnoremap <silent> <leader>gr :ALEFindReferences<CR>


" ---------- Autocmds ---------- "
augroup myAutocmds
    autocmd!
    " Source vimrc on save
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
    " Set mark C on last visited .c/.cpp file
    autocmd BufLeave *.{c,cpp} mark C
    " Set mark H on last visited .h file
    autocmd BufLeave *.h       mark H
    autocmd Filetype c,python setlocal omnifunc=ale#completion#OmniFunc
augroup END


" ---------- Airline config ---------- "
let g:airline_powerline_fonts = 1 
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"


" ---------- Terminfo config ---------- "
" Number of terminal colors
set t_Co=16

" Styled and colored underline support
let &t_AU = "\e[58:5:%dm"
let &t_8u = "\e[58:2:%lu:%lu:%lum"
let &t_Us = "\e[4:2m"
let &t_Cs = "\e[4:3m"
let &t_ds = "\e[4:4m"
let &t_Ds = "\e[4:5m"
let &t_Ce = "\e[4:0m"
" Strikethrough
let &t_Ts = "\e[9m"
let &t_Te = "\e[29m"
" Truecolor support
let &t_8f = "\e[38:2:%lu:%lu:%lum"
let &t_8b = "\e[48:2:%lu:%lu:%lum"
let &t_RF = "\e]10;?\e\\"
let &t_RB = "\e]11;?\e\\"
" Bracketed paste
let &t_BE = "\e[?2004h"
let &t_BD = "\e[?2004l"
let &t_PS = "\e[200~"
let &t_PE = "\e[201~"
" Cursor control
let &t_RC = "\e[?12$p"
let &t_SH = "\e[%d q"
let &t_RS = "\eP$q q\e\\"
let &t_SI = "\e[5 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[1 q"
let &t_VS = "\e[?12l"
" Focus tracking
let &t_fe = "\e[?1004h"
let &t_fd = "\e[?1004l"
" Window title
let &t_ST = "\e[22;2t"
let &t_RT = "\e[23;2t"
" vim hardcodes background color erase even if the terminfo file does not contain bce. This causes incorrect background
" rendering when using a color theme with a background color in terminals such as kitty that do not support background
" color erase.
let &t_ut=''


" ---------- Tinted Theming config ---------- "
" Set base color scheme
if filereadable(expand("$HOME/.config/tinted-theming/set_theme.vim"))
  let base16colorspace=256
  source $HOME/.config/tinted-theming/set_theme.vim
endif
" Set airline color theme
if filereadable(expand("$HOME/.config/tinted-theming/set_airline_theme.vim"))
  let base16colorspace=256
  source $HOME/.config/tinted-theming/set_airline_theme.vim
endif
