set ignorecase
set smartcase

set backspace=indent,eol,start

set number
set hlsearch

set hidden
set splitbelow
set splitright
set nowrap

"size of <tab>
set tabstop=4
"size of reindenting and << >> ==
set shiftwidth=4
"override filetype plugin (?)
set noexpandtab
"keep indentation of last line
set autoindent
"enable filetype plugin
"plugin customization available in ~/.vim/after/ftplugin
filetype plugin indent on

set mouse=a
set ttymouse=sgr

"<Leader> is backslash (\)
nmap <Leader>s :source $MYVIMRC<CR>
nmap <Leader>v :e $MYVIMRC<CR>

