set nocompatible

set ignorecase
set smartcase

set backspace=indent,eol,start

set number
set hlsearch

set hidden
set splitbelow
set splitright
set nowrap

set display=lastline

set background=dark

"size of <tab>
set tabstop=4
"size of reindenting and << >> ==
set shiftwidth=4
set shiftround
"override filetype plugin (?)
set noexpandtab
"keep indentation of last line
set autoindent
"enable filetype plugin
"plugin customization available in ~/.vim/after/ftplugin
filetype plugin indent on
syntax on
packadd! matchit

set ttyfast
set lazyredraw

set mouse=a
set ttymouse=sgr

set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo

"<Leader> is backslash (\)
nnoremap <Leader>s :source $MYVIMRC<CR>
nnoremap <Leader>v :e $MYVIMRC<CR>
vnoremap <Leader>y :OSCYank<CR>
nnoremap <Leader>Y v$:OSCYank<CR>
nnoremap <Leader>yy V:OSCYank<CR>
