#!/bin/bash

GIT_USER="$(git config user.name)"
GIT_EMAIL="$(git config user.email)"

cat << !
--- current git config ---
   user: "$GIT_USER"
  email: "$GIT_EMAIL"
--------------------------
!

if readYN "Is this the user you want to restrict this repository to?" 'y'; then
elif readYN "Run switchgit?" 'y'; then
	switchgit
fi



GIT_USER="$(git config user.name)"
while [[ "$GIT_USER" != "exdeejay" ]]; do
	# get stdin from keyboard
	exec < /dev/tty
	echo "ERROR: git user.name is set to \"$GIT_USER\""
	echo "(If you're not exdeejay, run \`rm .githooks/pre-commit\` to make this message go away)"
	echo
	if readYN "Run \`switchgit\`?" 'y'; then
		switchgit
		echo
		GIT_USER="$(git config user.name)"
	else
		exit 1
	fi
done

