#!/usr/bin/env bash

SLEEP_DELAY=30

# set the icon and a temporary location for the screenshot to be stored
#icon="$HOME/images/lock-icon-light.png"
tmpbg='/tmp/screen.png'

# take a screenshot
scrot "$tmpbg"

# blur the screenshot by resizing and scaling back up
mogrify -scale 10% -scale 1000% "$tmpbg"

# overlay the icon onto the screenshot
#convert "$tmpbg" "$icon" -gravity center -composite "$tmpbg"

# lock the screen with the blurred screenshot
i3lock -i "$tmpbg"
sleep $SLEEP_DELAY; pgrep i3lock && xset dpms force off

